import { FALLBACK_CATALOG } from '../fallbackCatalog';
import { isCustomerFacingCategory, toUiCategories } from '../../services/catalog/categoryAdapter';
import { toUiProducts } from '../../services/catalog/productAdapter';

/**
 * Guards the bundled catalog — what a guest, or anyone before sign-in, sees.
 *
 * It is generated by scripts/gen-fallback.mjs from a real verify response, so
 * these assertions are about SHAPE and INTERNAL CONSISTENCY rather than exact
 * counts wherever a count would simply churn on the next refresh. The two
 * hard-coded totals below are the ones worth pinning: they caught a truncated
 * capture before.
 */
describe('FALLBACK_CATALOG', () => {
  const { categories, products } = FALLBACK_CATALOG;

  it('carries the whole captured payload', () => {
    expect(categories).toHaveLength(19);
    expect(products).toHaveLength(146);
  });

  it('has no duplicate category or product ids', () => {
    expect(new Set(categories.map((c) => c.id)).size).toBe(categories.length);
    expect(new Set(products.map((p) => p.id)).size).toBe(products.length);
  });

  it('gives every category and product a non-empty name', () => {
    expect(categories.filter((c) => !c.name?.trim())).toEqual([]);
    expect(products.filter((p) => !p.name?.trim())).toEqual([]);
  });

  // A product pointing at a category id that does not exist would silently
  // vanish from every listing while still inflating the all-products count.
  it('files every product under a category or sub-service that exists', () => {
    const known = new Set<number>();
    for (const category of categories) {
      known.add(category.id);
      for (const child of category.subService ?? []) known.add(child.id);
    }
    const orphans = products.filter((p) => !known.has(p.categoryId));
    expect(orphans.map((p) => `${p.id} ${p.name} -> ${p.categoryId}`)).toEqual([]);
  });

  it('has a sane price and discount on every product', () => {
    const bad = products.filter(
      (p) =>
        typeof p.price !== 'number' ||
        p.price <= 0 ||
        p.discountPercentage < 0 ||
        p.discountPercentage > 100
    );
    expect(bad.map((p) => `${p.name}: ${p.price} / ${p.discountPercentage}%`)).toEqual([]);
  });
});

describe('FALLBACK_CATALOG through the adapters', () => {
  it('shows 18 customer-facing categories, hiding the seed row', () => {
    const uiCategories = toUiCategories(FALLBACK_CATALOG);
    expect(uiCategories).toHaveLength(18);
    expect(uiCategories.map((c) => c.name).filter((n) => /\bdemo\b/i.test(n))).toEqual([]);
  });

  it('hides the seed products too, so the counts agree with the listing', () => {
    const uiProducts = toUiProducts(FALLBACK_CATALOG);
    const hidden = FALLBACK_CATALOG.categories.filter((c) => !isCustomerFacingCategory(c));

    // Every category the adapter hides must take its products with it.
    const hiddenIds = new Set<number>();
    for (const category of hidden) {
      hiddenIds.add(category.id);
      for (const child of category.subService ?? []) hiddenIds.add(child.id);
    }
    const expectedVisible = FALLBACK_CATALOG.products.filter((p) => !hiddenIds.has(p.categoryId));
    expect(uiProducts).toHaveLength(expectedVisible.length);
  });

  // This is the invariant a user would notice: the number on the all-products
  // screen has to equal the sum of the numbers on the category cards.
  it('makes the category counts add up to the visible product total', () => {
    const total = toUiCategories(FALLBACK_CATALOG).reduce((sum, c) => sum + c.productCount, 0);
    expect(total).toBe(toUiProducts(FALLBACK_CATALOG).length);
  });
});
