const {
  withAppBuildGradle,
  withProjectBuildGradle,
  withDangerousMod,
} = require('@expo/config-plugins');
const path = require('path');
const fs = require('fs');

// android/ is gitignored and regenerated by `expo prebuild`, so anything Detox
// needs there (test runner config, androidTest deps, the DetoxTest instrumentation
// class) has to be re-applied by a config plugin instead of being committed directly.

function withDetoxProjectRepo(config) {
  return withProjectBuildGradle(config, (config) => {
    const marker = 'node_modules/detox/Detox-android';
    if (!config.modResults.contents.includes(marker)) {
      config.modResults.contents = config.modResults.contents.replace(
        /allprojects\s*{\s*repositories\s*{/,
        (match) => `${match}\n    maven { url "$rootDir/../node_modules/detox/Detox-android" }`
      );
    }
    return config;
  });
}

function withDetoxAppGradle(config) {
  return withAppBuildGradle(config, (config) => {
    let contents = config.modResults.contents;

    if (!contents.includes('testInstrumentationRunner')) {
      contents = contents.replace(
        /versionName\s+"[^"]*"/,
        (match) =>
          `${match}\n        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"\n        testBuildType System.getProperty('testBuildType', 'debug')\n        missingDimensionStrategy 'detox', 'full'`
      );
    }

    if (!contents.includes('com.wix:detox')) {
      contents = contents.replace(
        /dependencies\s*{/,
        (match) =>
          `${match}\n    androidTestImplementation('com.wix:detox:+')\n    androidTestImplementation 'androidx.test:runner:1.5.2'\n    androidTestImplementation 'androidx.test:rules:1.5.0'`
      );
    }

    config.modResults.contents = contents;
    return config;
  });
}

function withDetoxTestClass(config) {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const packageName = config.android?.package;
      if (!packageName) return config;

      const packagePath = packageName.split('.').join('/');
      const dir = path.join(
        config.modRequest.platformProjectRoot,
        'app/src/androidTest/java',
        packagePath
      );
      fs.mkdirSync(dir, { recursive: true });

      const filePath = path.join(dir, 'DetoxTest.java');
      const contents = `package ${packageName};

import com.wix.detox.Detox;
import com.wix.detox.config.DetoxConfig;

import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.rule.ActivityTestRule;
import androidx.test.filters.LargeTest;

import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(AndroidJUnit4.class)
@LargeTest
public class DetoxTest {
    @Rule
    public ActivityTestRule<MainActivity> mActivityRule = new ActivityTestRule<>(MainActivity.class, false, false);

    @Test
    public void runDetoxTests() {
        DetoxConfig detoxConfig = new DetoxConfig();
        detoxConfig.idlePolicyConfig.masterTimeoutSec = 90;
        detoxConfig.idlePolicyConfig.idleResourceTimeoutSec = 60;
        detoxConfig.rnContextLoadTimeoutSec = (BuildConfig.DEBUG ? 180 : 8);

        Detox.runTests(mActivityRule, detoxConfig);
    }
}
`;
      fs.writeFileSync(filePath, contents);
      return config;
    },
  ]);
}

module.exports = function withDetoxAndroid(config) {
  config = withDetoxProjectRepo(config);
  config = withDetoxAppGradle(config);
  config = withDetoxTestClass(config);
  return config;
};
